config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'signup', to: 'users#new'
  resources :users, except: :new do
    resources :categories
    resources :tasks
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  before_save { name.downcase! }
  belongs_to :user
  validates :name, presence: true, uniqueness: { case_sensitive: false}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :firstname, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category, only: %i[show edit update destroy]
  before_action :get_user
  before_action :set_category, only: %i[show edit update destroy]
  before_action :require_login

  def index
    @categories = @user.categories
  end

  def show
  end

  def new
    @category = @user.categories.build
  end
  
  def edit
  end

  def create
    @category = @user.categories.build(category_params)
    if @category.save
      redirect_to [@user, @category], notice: 'Category was created successfully'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to [@user, @category], notice: 'Category was updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to user_categories_path, notice: 'Category was deleted successfully'
  end

  private

  def get_user 
    @user = User.find(params[:user_id])
  end
  
  def set_category
    @category = @user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :user_id)  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: 'Login successful'
    else
      flash[:alert] = 'Invalid username or password'
      render :new
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: %i[ show edit update destroy]

    def index
        @tasks = Task.all
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.create(task_params)
        redirect_to @task
    end

    def edit
    end

    def update
        @task.update! (task_params)
        redirect_to @task
    end

    def show
    end

    def destroy
        @task.destroy
        redirect_to tasks_path, notice: 'Task was deleted successfully'
      end

    private

    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:todo, :due, :notes)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'Account was created successfully'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @user_tasks_today = @user.tasks.where(due: Date.today.beginning_of_day..Date.today.end_of_day)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:firstname, :lastname, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_to_propercase(string)
    arr_of_str = string.split(' ')
    arr_of_str.map! { |word| word.capitalize }
    arr_of_str.join(' ')
  end
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with model: [@user, @category], local: true do |form| %>
  <div class='mb-3'>
    <%= form.label :name, class: 'form-label' %>  
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter category name' %>
  </div>
  <%= form.submit class: 'btn btn-primary col-md-4 me-3' %>

<% end %>

app/views/categories/edit.html.erb
<section class='container-fluid p-5'>
  <h1 class='mb-3'>Edit category</h1>
  <%= render 'form' %>
</section>

app/views/categories/index.html.erb
<section class='container-fluid p-5'>
<div class='d-flex'>
  <h1>Categories</h1>
  <%= link_to 'New Category', new_user_category_path, class: 'align-self-center btn btn-primary ms-5 px-5 py-2 rounded-pill shadow' %>
</div>
  <table class='table table-hover mt-4' id='categories-list'>
    <thead>
      <tr class='table-primary'>
        <th>Category</th>
        <th colspan='3' class='text-center'>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= convert_to_propercase(category.name) %></td>
        <td><%= link_to 'Show', user_category_path(@user, category), class: 'btn btn-primary btn-sm'%></td>
        <td><%= link_to 'Edit', edit_user_category_path(@user, category), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Delete', user_category_path(@user, category), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary btn-sm' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/categories/new.html.erb
<section class='container-fluid p-5'>
  <h1 class='mb-3'>Create new category</h1>
  <%= render 'form' %>
</section>

app/views/categories/show.html.erb
<section class='container-fluid p-5'>
  <h1 class='mb-3'><%= convert_to_propercase(@category.name) %></h1>
</section>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger'%> alert-dismissible fade show" role="alert">
        <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark min-vh-100" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">JournalApp</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"/></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"/></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"/></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico')  %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <div class='d-flex'>
    <% if logged_in? %>
      <%= render 'layouts/navigation' %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade row show" role="alert">
	<h2 class="alert-heading">Uh-oh! Something went wrong</h2>
  <p>The following errors prevented the <%= obj.class.name.downcase %> from being saved:</p>
  <hr>
	<ul class='ms-2'>
    <% obj.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |form| %>
  <div class='mb-3'>
    <%= form.label :todo, class: 'form-label' %>  
    <%= form.text_field :todo, class: 'form-control' %>
  </div>

<div class='mb-3'>
    <%= form.label :due, class: 'form-label' %>
    <%= form.datetime_field :due, min: Date.today %>
  </div>

  <div class='mb-3'>
    <%= form.label :notes, class: 'form-label' %>  
    <%= form.text_field :notes, class: 'form-control' %>
  </div>

  <%= form.submit "Submit task", class: 'btn btn-primary col-md-4 me-3' %>

<% end %>

app/views/tasks/create.html.erb
<h1><%= @task.todo %></h1>
<div><%= @task.due %></div>
<div><%= @task.notes %></div>

app/views/tasks/edit.html.erb
<section class='container-fluid p-5'>
  <h1 class='mb-3'>Edit task</h1>
  <%= render 'form' %>
</section>

app/views/tasks/index.html.erb
<section class='container-fluid p-5'>
<div class='d-flex'>
  <h1>Tasks</h1>
  <%= link_to 'New Task', new_user_task_path, class: 'align-self-center btn btn-primary ms-5 px-5 py-2 rounded-pill shadow' %>
</div>
  <table class='table table-hover mt-4' id='tasks-list'>
    <thead>
      <tr class='table-primary'>
        <th>Task</th>
        <th>Due</th>
        <th>Notes</th>
        <th colspan='3' class='text-center'>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr>
        <td><%= task.todo %></td>
        <td><time><%= task.due.strftime('%b %e, %Y %I:%M %P') %></time></td>
        <td><%= task.notes %></td>
        <td><%= link_to 'Show', [@user, task], class: 'btn btn-primary btn-sm'%></td>
        <td><%= link_to 'Edit', edit_user_task_path(@user, task), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Delete', [@user, task], method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary btn-sm' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/tasks/new.html.erb
<section class='container-fluid p-5'>
  <h1 class='mb-3'>Create new Task</h1>
  <%= render 'form' %>
</section>

app/views/tasks/show.html.erb
<h1><%= @task.todo %></h1>
<div><%= @task.due %></div>
<div><%= @task.notes %></div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%= form_with model: @user, class: 'my-3' do |f| %>
  <%= f.label :firstname, 'First Name', class: 'form-label' %>
  <%= f.text_field :firstname, required: true, class: 'form-control' %>
  <%= f.label :lastname, 'Last Name', class: 'form-label mt-3' %>
  <%= f.text_field :lastname, class: 'form-control' %>
  <%= f.label :username, 'Username', class: 'form-label mt-3' %>
  <%= f.text_field :username, required: true, class: 'form-control' %>
  <%= f.label :password, 'Password', class: 'form-label mt-3' %>
  <%= f.password_field :password, required: true, class: 'form-control' %>
  <%= f.label :password_confirmation, 'Confirm Password', class: 'form-label mt-3' %>
  <%= f.password_field :password_confirmation, required: true, class: 'form-control' %>
  <%= f.submit 'Create Account', class: 'btn btn-primary mt-4 col-12' %>
<% end %>

app/views/users/new.html.erb
<main class='container-fluid row p-0 m-0 position-relative' id='homepage'>
  <div class="col-7 img-container d-none d-md-block">
    <%= image_tag asset_path('todolist.svg'), class: 'img-fluid' %>
  </div>
  <div class="p-5 col-md-5 container-md pb-15">
    <h1>Sign Up</h1>
    <%= render 'form' %>
    <p>Already have an account? <%= link_to 'Log in', login_path, class: 'link-primary' %></p>
  </div>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" class='position-absolute bottom-0 p-0'>
    <path fill="#023047" fill-opacity="1" d="M0,64L48,96C96,128,192,192,288,229.3C384,267,480,277,576,250.7C672,224,768,160,864,160C960,160,1056,224,1152,256C1248,288,1344,288,1392,288L1440,288L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path>
  </svg>
</main>

app/views/users/show.html.erb
<section class='p-5 w-100'>
<h3 class='text-muted'>Welcome <%= @user.firstname %>!</h3>
<h1>You have <%= @user.tasks.count %> tasks for today</h1>
  <div class="card">
    <h5 class="card-header">Due for today</h5>
    <div class="card-body">
      <ul class="list-group list-group-flush card-text">
        <% if @user_tasks_today.any? %>
          <% @user_tasks_today.each do |task| %>
            <li class='list-group-item'><%= task.todo %></li>
          <% end %>
        <% else %>
          <li class='list-group-item'>No due tasks for today.</li>
        <% end %>        
      </ul>
      <%= link_to 'Create new task', new_user_task_path(@user), class: 'btn btn-primary mt-3 px-5' %> 
    </div>
  </div>
</section>